name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push the Docker image
      run: |
        docker build -t 207080326074.dkr.ecr.ap-southeast-1.amazonaws.com/flask_blog:${{ github.sha }} .
        docker tag 207080326074.dkr.ecr.ap-southeast-1.amazonaws.com/flask_blog:${{ github.sha }} 207080326074.dkr.ecr.ap-southeast-1.amazonaws.com/flask_blog:latest
        docker push 207080326074.dkr.ecr.ap-southeast-1.amazonaws.com/flask_blog:${{ github.sha }}
        docker push 207080326074.dkr.ecr.ap-southeast-1.amazonaws.com/flask_blog:latest
